### ISSUE TITLE
Enabling this package stops auto complete from working correctly

### ISSUE THREAD

**Issue by AlexNodex** [php-integrator/atom-autocompletion#102]
Hi.

A while ago my auto complete stopped working, I decided to investigate why, I've disabled packages until it started working properly and as a result found out that this package was the culprit.

If I disabled this my own auto complete snippets work but the core PHP code snippets don't work, if I enable it then nothing works!

I am not sure how to debug this to fix it

**Comment by Gert-dev** [comment]
Atom's `language-php` package ships with some default suggestions, such as built-in global PHP functions. These are rather barebones and since php-integrator ships much more detailed versions of the same suggestions, this package disables the built-in PHP suggestions, which explains why you can't see the default suggestions.

Snippets in your custom snippets should remain functional with or without this package (I'm using both as well).

If no suggestions display after enabling this, it is possible that no suggestions are being provided by the base package or core. (The built-in suggestions are disabled in the Atom package itself, so they will be disabled whether php-integrator is working properly or not.) Have you successfully followed and set up your project as described in [1] and [2] and does your project start indexing?

[1] https://php-integrator.github.io/#what-do-i-need
[2] https://github.com/php-integrator/atom-base/wiki/Help!-It-Doesn't-Work!

**Comment by Gert-dev** [comment]
Closing due to age and inactivity.
