### ISSUE TITLE
Very slow in atom

### ISSUE THREAD

**Issue by jamb84** [php-integrator/atom-autocompletion#107]
Hi,
I had been having major issues with the autocompletion speed recently and I found the closed issue [https://github.com/php-integrator/atom-autocompletion/issues/103](url) in which there was a description of why the issue occurs.

Since waiting for the migration of autocompletion into core isn't likely going to happen any time soon, I went about implementing a temporary fix for the issue. Unfortunately it requires patches to atom-base and the 3.1.0 core inside it, and atom-autocompletion to make it work.

After applying these patches, each of the jsonRpcResponse objects will generate a hash of the result element and relay it back - if the hash is the same as the one that has been submitted in the request it will empty the result.

On the atom side it will compare the hash in the successHandler and if it's the same it just returns. If it's different it will update the list. It stores the latest hash against the provider for resubmission with the next request.

As a result of this I have been able to drop my jitter time to 0 and my delay time to 500 and everything is working beautifully quick.

I know it's not the best solution, but it's a reasonable workaround in the interim.
[patches.zip](https://github.com/php-integrator/atom-autocompletion/files/1508326/patches.zip)

**Comment by Gert-dev** [comment]
Thanks for the tip. As you know, I'm aware of this and it is [actually the next thing on the roadmap](https://gitlab.com/php-integrator/core/issues/43) as it is, now that a lot of other issues have been cleared out of the way, one of the remaining annoyances and performance lags that remain.

After this is fixed, it's probably going to shift to being request cancellation not being implemented, and so progress continues 😄.

In any case, I'll close this since it's already being tackled in another issue report, but thanks for taking the time to write out a temporary fix.
