### ISSUE TITLE
use statement autocomplete requires typing first letter of FQCN

### ISSUE THREAD

**Issue by tocjent** [php-integrator/atom-autocompletion#42]
From what I investigated in the package, matching text is done by the autocomplete-plus package provided by Atom, however I'm not sure about that.

The steps to reproduce are (illustrated by EntityManager class from Doctrine2):
1. Open a Doctrine2 project (i.e. [symfony-standard](https://github.com/symfony/symfony-standard))
2. In a PHP file type 'use EntityManager'
3. No suggestions are displayed
4. Change typed text to 'use DEntityManager'
5. Suggestion for 'Doctrine\ORM\EntityManager' is displayed

This issue is more of a question: could autocomplete suggestions match relative class name (as above)? Sadly, my investigation of autocomplete Provider API and your code was inconclusive.

**Comment by Gert-dev** [comment]
Your deduction was correct; in the past matching the various items (class names, method names, etc.) happened by manually invoking fuzzaldrin with the prefix the user typed. However, a while ago, autocomplete-plus gained support for doing filtering all by itself, so this code has been removed since a couple of versions ago. In other words, fuzzy matching is now completely managed by autocomplete-plus. This has led to a couple of frustrations for me as well:
* The matching is not always great. I've taken another look at the use statement class provider, and it is correctly providing all the known classes to autocomplete-plus, which then proceeds with filtering and somehow decides that items that have the typed text, but prefixed with a namespace, should be ignored. It could also be that I'm just using the functionality from autocomplete-plus incorrectly.
* The most annoying is by far #15. If you happen to have two classes with the same name, one of them won't show up. It doesn't even matter if they are not in the same namespace, as when inserting them, they will both insert the same text: only the class name, as the use statement for it is automatically added afterwards. autocomplete-plus picks this up as being a duplicate, while the text both completions are displaying is entirely different as they come from different namespaces.

**Comment by Gert-dev** [comment]
I'm going to close this issue as it now definitely seems to be an issue with autucomplete-plus, which I've reported here [1]. It seems to be easy to fix on their side, but sadly development and issue solving hasn't exactly been active on the package lately.

[1] https://github.com/atom/autocomplete-plus/issues/777
