### ISSUE TITLE
Do not add use statement in the same namespace

### ISSUE THREAD

**Issue by vitalybaev** [php-integrator/atom-autocompletion#60]
Autocomplete adds use statement even Class in the same namespace.

<img width="430" alt="2016-08-02 14 32 31" src="https://cloud.githubusercontent.com/assets/724423/17327041/63b2345e-58c6-11e6-8f9e-10a322834176.png">

**Comment by Gert-dev** [comment]
This _should_ be working, but I've noticed that in some rare cases (I've yet to discover when) it decides that it is in a different namespace. Marking as bug.

**Comment by Gert-dev** [comment]
I recently had this again and had a chance to debug why this is happening. It turns out it only happens for class autocompletion outside classes: such as after the `implements` or `extends` keyword because the "current class" (and its accompanying FQCN and namespace) can't be fetched.

(I'm just putting this information here as a reminder to my possibly later self.)
