### ISSUE TITLE
Improve autocompleted PHP tag

### ISSUE THREAD

**Issue by sitedrive** [php-integrator/atom-autocompletion#73]
**Problem:** When typing "<?php" and pressing the return key, autocomplete prevents new line insertion.

**Expected result:** A blank line is inserted below the opening tag, followed by "?>" on another line. (where | is cursor).
```
<?php
|
?>
```

**Current result:** All pieces are inserted in the same line with extra whitespace (where | is cursor).
`<?php | ?> `

**Proposed solution:** Add an option to disable this specific autocompletion/snippet, or fix the newline problem.

**Comment by sitedrive** [comment]
The current workaround is to type a space before hitting return key, but I don't like unnecessary whitespace so I always end up going back and removing the extra space. :(

**Comment by Gert-dev** [comment]
I'm not sure I can fix this, as the problematic snippet is not provided by this package, but by the `language-php` Atom package [1]. To make matters worse, autocomplete-plus (which actually displays and filters the suggestions, I just provide the possibilities) is not very good at mixing results of multiple providers [2], in this case the snippets from language-php and the suggestions from this package.

What you may be able to do is define a custom snippet in your Atom snippets that has the same shorthand as the one from language-php and override the value to contain a newline. You could also submit a pull request for `language-php` to fix it, but I have a hunch that this is intended behavior on their side.

[1] https://github.com/atom/language-php/blob/master/snippets/language-php.cson#L5
[2] https://github.com/atom/autocomplete-plus/issues/465

**Comment by sitedrive** [comment]
Really? That's pretty interesting, because it wasn't doing it when I had PHP Integrator disabled. But I will head over to `language-php` then. Thanks.

**Comment by Gert-dev** [comment]
To be sure, I tried disabling `php-integrator-autocomplete-plus` and still seem to experience the problem: typing `<?php` will display `language-php` autocompletion for the accompanying snippet. Pressing return afterwards expands the snippet to `<?php   ?>` instead of a newline.

I agree that it is frustrating however, and I've also been running into this myself. Perhaps the reason this snippet is present is for HTML files or templates that want to use this snippet to mingle them with PHP code.
