### ISSUE TITLE
autocomplete with parameters 

### ISSUE THREAD

**Issue by hamedshahien** [php-integrator/atom-autocompletion#92]
Hello , 
great package 

I see the function in suggestion list like this 
`getValue($array, $key, $default = null)
`
could i return function like this 
`getValue($array, $key, $default = null)
`
instead of this
 
`getValue()`

I don't care about showing parameters . I need auto complete to write it instead of showing it .

**Comment by Gert-dev** [comment]
Thanks! Do you mean that visually, in the autocompletion dropdown, everything stays the same, but instead of inserting just `getValue()`, it inserts `getValue($array, $key, $default = null)`? Initially, this was the way it worked, you then had to use tab to jump between the inserted parameter placeholders.

In practice, I found that this was rather annoying as the placeholders are really just that: placeholders, in some rare cases, the name of the parameter `$array` happens to also be the name of a local variable and you could leave the placeholder as is, but usually you had to remove all of the parameters and fill them in with what you actually want to pass.

Instead, I decided to take a glimpse at how IDE's usually handle this and they operate the same as it currently does in this package, with the exception that you get call tips between the parantheses after completion. For this reason, I developed the [php-integrator-call-tips](https://atom.io/packages/php-integrator-call-tips) package to do just that. You basically select the match you want from the autocompletion box, this is inserted:

```
// The bar is where the cursor will be at.
getValue(|)
```

... and the call tips package will show you what you need to insert as parameter next:

![call-tips](https://cloud.githubusercontent.com/assets/24809863/22346728/0d6777fe-e3fd-11e6-840b-4b0c63230879.png)

**Comment by hamedshahien** [comment]
ok. thanks alot.
